FROM docker_base:latest

USER root

# Build ROS2 node
COPY navigation.node/navigation /navigation/navigation
RUN cd /navigation/navigation && \
    source /opt/ros/eloquent/setup.bash && \
    colcon build
