version: '3.3'

services:
  
  logger:
    build:
      context: .
      dockerfile: Dockerfile.ros2
    command: bash -c "source /opt/ros/eloquent/setup.bash && ros2 run demo_nodes_cpp listener"
    # healthcheck:
    #   test: bash -c "source /opt/ros/eloquent/setup.bash && ros2 node info /listener" || exit 1
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3
    restart: on-failure
    environment:
      - ROS_DOMAIN_ID=0
      - ROS_LOCALHOST_ONLY=0

  navigation:
    build:
      context: ..
      dockerfile: docker/Dockerfile.navigation
    devices:
      # Need all the i2c devices
      - /dev/i2c-0
      - /dev/i2c-1
      - /dev/i2c-2
      - /dev/i2c-3
      - /dev/i2c-4
      - /dev/i2c-5
      - /dev/i2c-6
    command: bash -c "source /opt/ros/eloquent/setup.bash && source /navigation/navigation/install/setup.bash && ros2 run navigation interpreter"
    environment:
      - ROS_DOMAIN_ID=0
      - ROS_LOCALHOST_ONLY=0
    restart: on-failure
    depends_on:
      - logger
  
  whisper:
    build:
      context: ..
      dockerfile: docker/Dockerfile.whisper    
    command: bash -c "source /opt/ros/eloquent/setup.bash && source /whisper/voice_commands/install/setup.bash && ros2 run voice_commands stream_listener"
    devices:
      - /dev/snd:/dev/snd
    restart: on-failure
    depends_on:
      - logger
      - navigation
