version: '3.3'

services:
  
  # base:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.ros2
  #   # platform: linux/arm64
  #   # network_mode: host
  #   command: bash -c "source /opt/ros/eloquent/setup.bash && sleep 10 && echo Topic list && ros2 topic list && echo Node list && ros2 node list && sleep 86400"

  whisper:
    build:
      context: ..
      dockerfile: docker/Dockerfile.whisper    
    command: bash -c "source /opt/ros/eloquent/setup.bash && source /whisper/voice_commands/install/setup.bash && ros2 run voice_commands stream_listener"
    devices:
      - /dev/snd:/dev/snd

  # talker:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.ros2
  #   # platform: linux/arm64
  #   # network_mode: host
  #   command: bash -c "source /opt/ros/eloquent/setup.bash && ros2 run demo_nodes_cpp talker"
  #   environment:
  #     - ROS_DOMAIN_ID=0
  #     - ROS_LOCALHOST_ONLY=0
  
  listener:
    build:
      context: ..
      dockerfile: docker/Dockerfile.navigation
    # platform: linux/arm64
    # network_mode: host
    command: bash -c "source /opt/ros/eloquent/setup.bash && source /navigation/navigation/install/setup.bash && ros2 run navigation interpreter"
    depends_on:
      - whisper
  
  # check:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.ros2
  #   # platform: linux/arm64
  #   # network_mode: host
  #   command: bash -c "source /opt/ros/eloquent/setup.bash && while sleep 10; do echo Topic list ; ros2 topic list; done"
  #   environment:
  #     - ROS_DOMAIN_ID=0
  #     - ROS_LOCALHOST_ONLY=0
  #     - TERM=xterm
  #   depends_on:
  #     - whisper
  #     - listener

