FROM nvcr.io/nvidia/l4t-pytorch:r32.5.0-pth1.6-py3

# Build whisper
COPY ./whisper.cpp /whisper

WORKDIR /whisper

# Install pre-requisite
RUN apt-get update && \
    apt-get install -y libsdl2-dev

RUN cd /whisper && \
    make clean && \
    WHISPER_CUBLAS=1 make -j stream
